 DROP TABLE IF EXISTS transaction;
 DROP TABLE IF EXISTS adres;
 
 CREATE TABLE TRANSACTION (
     ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
     SYGNATURA        VARCHAR(20), 
     SYMBOL           VARCHAR(20), 
     ODBIORCA         VARCHAR(150), 
     DATA             DATE, 
     DATA_WY          DATE,
     ID_NEW           INTEGER,
     PRZYCHODZACY     BOOLEAN,
     POLECONY         BOOLEAN,
     OPIS             VARCHAR(500),
     WEWN             BOOLEAN
 )

 CREATE TABLE ADRES (
     ID_NEW     INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
     IMIE        VARCHAR(30)            DEFAULT '', 
     NAZWISKO    VARCHAR(50)            DEFAULT '', 
     FIRMA        VARCHAR(150)        DEFAULT '', 
     ULICA        VARCHAR(80)            DEFAULT '', 
     MIASTO        VARCHAR(40)            DEFAULT '', 
     KOD        VARCHAR(20)            DEFAULT '', 
     TEL1        VARCHAR(30)         DEFAULT '', 
     TEL2        VARCHAR(30)            DEFAULT '', 
     FAX        VARCHAR(20)            DEFAULT '', 
     MAIL        VARCHAR(50)            DEFAULT '', 
     NOTATKI    VARCHAR(255)        DEFAULT ''
);

 ALTER TABLE TRANSACTION ADD FOREIGN KEY (ID_NEW) REFERENCES ADRES(ID_NEW);

 CREATE INDEX iddesc ON transaction (sygnatura) ;
 CREATE INDEX idnew ON transaction (ID_NEW);
 CREATE INDEX isymbolt ON transaction (SYMBOL);
 CREATE INDEX iodbt ON transaction (ODBIORCA);
 CREATE INDEX idnewadr ON adres (ID_NEW) ;
 CREATE INDEX indimadr ON adres (IMIE) ;
 CREATE INDEX inazadr ON adres (NAZWISKO) ;
 CREATE INDEX ifirmaadr ON adres (FIRMA) ;
 CREATE INDEX iulicaadr ON adres (ULICA) ;
 CREATE INDEX imiastoadr ON adres (MIASTO) ;
